import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import cleaner
import matplotlib.pyplot as plt
import numpy as np


# Input: filename/path of csv file generated by melk gatherer.
# Output: new csv file with additional columns for sentiment value
def add_sentiment_scores(csv):
    # clean data
    df = cleaner.main(csv)

    # add column with sentiment scores initialized to zero
    df["SENTIMENT"] = 0

    print(df.head(5))

    df["SENTIMENT"] = [score_sentiment(text) for text in df["FULL_TEXT"]]

    print(df.head(30))

    # df['SENTIMENT']  = df['FULL_TEXT'].apply(lambda r : analyzer.polarity_scores(r))

    df.to_csv(csv)

    return


def score_sentiment(text):
    # Rates sentiment of text between -1 and 1, based on vader sentiment analysis
    analyzer = SentimentIntensityAnalyzer()

    sentiment_dict = {"compound": None}

    try:
        sentiment_dict = analyzer.polarity_scores(text)
    except TypeError:
        print("This text caused an error: ", text)

    return sentiment_dict["compound"]


def sentiment_histogram(csv):
    # takes csv with 'SENTIMENT' column, returns sentiment score histogram
    df = pd.read_csv(csv)
    hist = plt.hist(df["SENTIMENT"])
    plt.xlabel("Sentiment score")
    plt.ylabel("Frequency")
    # plt.show()

    return hist
